FROM golang:1.16 AS builder

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    GOPROXY="https://goproxy.cn,direct"

WORKDIR /app-upgrade

COPY . .

EXPOSE 9090

ENTRYPOINT ["./main"]